7
A7 BLACK marble placed.
B6 WHITE marble placed.
A4 BLACK marble placed.
B4 WHITE marble placed.
A1 BLACK marble placed. Mill formed.
B4 BLACK removed piece.
B4 WHITE marble placed.
D1 BLACK marble placed.
B2 WHITE marble placed. Mill formed.
D1 WHITE removed piece.
C4 BLACK marble placed.
C5 WHITE marble placed.
D5 BLACK marble placed.
D6 WHITE marble placed.
F6 BLACK marble placed.
D7 WHITE marble placed.
D2 BLACK marble placed.
F2 WHITE marble placed.
F4 BLACK marble placed. Now in piece movement phase.
G4 WHITE marble placed. Now in piece movement phase.
F4 BLACK selected marble.
E4 BLACK moved marble here.
G4 WHITE selected marble.
G7 WHITE moved marble here.
F6 BLACK selected marble.
F4 BLACK moved marble here.
D6 WHITE selected marble.
F6 WHITE moved marble here.
D5 BLACK selected marble.
E5 BLACK moved marble here.
G7 WHITE selected marble.
G4 WHITE moved marble here.
E4 BLACK selected marble.
E3 BLACK moved marble here.
G4 WHITE selected marble.
G7 WHITE moved marble here.
F4 BLACK selected marble.
E4 BLACK moved marble here. Mill formed.
C5 BLACK removed piece.
F6 WHITE selected marble.
F4 WHITE moved marble here.
C4 BLACK selected marble.
C3 BLACK moved marble here.
F4 WHITE selected marble.
G4 WHITE moved marble here.
D2 BLACK selected marble.
D3 BLACK moved marble here. Mill formed.
F2 BLACK removed piece.
B6 WHITE selected marble.
D6 WHITE moved marble here.
E5 BLACK selected marble.
D5 BLACK moved marble here.
D6 WHITE selected marble.
F6 WHITE moved marble here.
D5 BLACK selected marble.
E5 BLACK moved marble here. Mill formed.
D7 BLACK removed piece.
F6 WHITE selected marble.
F4 WHITE moved marble here.
D3 BLACK selected marble.
D2 BLACK moved marble here.
F4 WHITE selected marble.
F2 WHITE moved marble here.
D2 BLACK selected marble.
D3 BLACK moved marble here. Mill formed.
F2 BLACK removed piece.
B4 WHITE selected marble.
B6 WHITE moved marble here.
C3 BLACK selected marble.
C4 BLACK moved marble here.
B6 WHITE selected marble.
D6 WHITE moved marble here.
C4 BLACK selected marble.
C3 BLACK moved marble here. Mill formed.
B2 BLACK removed piece.
D6 WHITE selected marble (fly rule).
B2 WHITE moved marble here (fly rule).
C3 BLACK selected marble.
C4 BLACK moved marble here.
B2 WHITE selected marble (fly rule).
G1 WHITE moved marble here (fly rule). Mill formed.
C4 WHITE removed piece.
E4 BLACK selected marble.
F4 BLACK moved marble here.
G1 WHITE selected marble (fly rule).
D2 WHITE moved marble here (fly rule).
F4 BLACK selected marble.
F6 BLACK moved marble here. Causing a game over.
